version: 2
jobs:
    build:
        docker:
            - image: garland/aws-cli-docker
        steps:
            - checkout

            - run:
                name: Deploy to S3
                command: aws --region eu-west-2 s3 sync ./templates s3://jakubigla-cf-templates/ --delete