---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  AWS CloudFormation Template that creates a Lambda function,
  which stops particular EC2 instances based on CloudWatch schedule
Resources:
  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: StopInstances
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: LambdaLogging
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - arn:aws:logs:*:*:*
              - Sid: EC2StopInstances
                Action:
                  - ec2:DescribeInstances
                  - ec2:StopInstances
                Effect: Allow
                Resource: "*"
  LambdaFunction:
    Properties:
      Code:
        ZipFile: |
          import boto3

          def handler(event, context):
              ec2       = boto3.resource('ec2', region_name='eu-west-2')
              filters   = []
              instances = []

              for eventTag in event['tags']:
                  filters.append({'Name': 'tag:' + eventTag['key'], 'Values': [eventTag['value']]})

              ec2.instances.filter(Filters=filters).stop()
      Description: |
        Stop or terminate EC2 instances that have a specific tag
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaIAMRole
          - Arn
      Runtime: python2.7
      Timeout: 120
    Type: AWS::Lambda::Function
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
          - LambdaFunction
          - Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - CloudWatchEventRule
          - Arn
  CloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 0 * * ? *)
      State: ENABLED
      Description: |
        Schedule stop of EC2 instances with the following tags:
        ProjectName=CulesWorld, Role=GitlabRunner
      Targets:
        - Arn:
            Fn::GetAtt:
              - LambdaFunction
              - Arn
          Id: StopInstancesFunction
          Input: |
            {
              "tags": [
                {
                  "key": "Role",
                  "value": "GitlabRunner"
                },
                {
                  "key": "ProjectName",
                  "value": "CulesWorld"
                }
              ]
            }
